### ISSUE TITLE
Does Loki have to be installed on the same host to Promtail?

### ISSUE THREAD

**Issue by k-szortyka** [brpaz/logs-with-loki#1]
Does Loki have to be installed on the same host to Promtail?
I would like ship all container logs to Loki but if I have 20 hosts to run Loki next to the Promtail it seems pointless. After all, the logs are shipped to one loki server. Did I get something wrong?

**Comment by brpaz** [comment]
No. You can configure the Loki host in the promtail configuration file, so you can have all your protmail instances pointing to the same Loki server.

Check: https://grafana.com/docs/loki/latest/clients/promtail/configuration/#clients

For more details, I recommend checking the documentation. The example on this repository is focused on having Loki run on your local development machine. It´s not a "production" like envrionment.
